// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangeIn struct {
	ID string `json:"id"`
}

type Sam struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Category string `json:"category"`
}

type SamIn struct {
	ID string `json:"id"`
}

type Seller struct {
	ApplicationNo string `json:"application_no"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	Status        string `json:"status"`
	SamID         string `json:"sam_id"`
}

type SellerDataIn struct {
	SellerID string  `json:"seller_id"`
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Status   *string `json:"status"`
	SamID    *string `json:"sam_id"`
}

type StatusIn struct {
	Status string `json:"status"`
}

type TransferIn struct {
	SellerID string `json:"seller_id"`
	SamID    string `json:"sam_id"`
	Msg      string `json:"msg"`
}
